### ISSUE TITLE
Error deploying HHypermap (Django)

### ISSUE THREAD

**Issue by CorMelse** [cga-harvard/HHypermap#125] opened 2016-08-03 13:27 UTC
[installHHM.txt](https://github.com/cga-harvard/HHypermap/files/399537/installHHM.txt)
While searching for a monitoring tool to gain insight in the use of QGC web services I found both GeoHealthCheck (GHC) and HHypermap (HHM).
As i succeeded installing GHC, I keep getting errors on HHM and I wonder if someone can help me out. 
Tom Kralidis replied on my mail with the request to create a ticket "for this looks like bug of some sort"

My laptop is a Ubuntu 16.04 LTS with python 2.7 (and 3.5) and following the description on the Github page I am getting to the final stage without any error.
But starting the " ./manage.py runserver " command Django crashes with an error (in the file attached)
Who can point me in the right direction to solve this? I've been googeling for the last 2 days to find a solution.

I  attached the install script i made from the readme.md (which works great until the last command ;-(  ) as well as the error generated by Django
[ErrorHHMinstall.txt](https://github.com/cga-harvard/HHypermap/files/399520/ErrorHHMinstall.txt)

btw: the skip_celery_task switch in the install script did not solve it.....

Thanx in advance, Cor

**Comment by JorgeMartinezG** [comment] 2016-08-03 16:23
Hello. The problem is that django looks for a wsgi.py file whose path is defined in settings folder. This path corresponds to HHypermap/hypermap/wsgi.py, but right now the file is in HHypermap/wsgi.py. I've created a PR that moves this file into hypermap folder.
Bests

**Comment by CorMelse** [comment] 2016-08-03 17:28
Thanx a million!
with the PR (i am new to github etc..) you mean that i have to clone the code again and it willinstall properly?
Cor

**Comment by tomkralidis** [comment] 2016-08-03 17:33
@CorMelse assuming you cloned master branch, once #128 is merged by the HHypermap team you can get updates with `git pull origin master` which will pull down the latest updates and try the install once more.

**Comment by tomkralidis** [comment] 2016-08-03 17:38
Fixed/merged in master.

**Closed by tomkralidis** 2016-08-03 17:38 UTC

**Comment by capooti** [comment] 2016-08-03 19:26
@JorgeMartinezG it seems that @CorMelse is running the Django development server, so no connection with wsgi.py. That one is generally used for production environment.

**Comment by capooti** [comment] 2016-08-03 20:31
Sorry, you are correct, it is using still a wsgi application specified by the  WSGI_APPLICATION settings. Just read the doc. It was me to move the file as per some reasons it wasn't working in that position. I reported this to @ingenieroariel 
My best guess is that I will still make it working by changing WSGI_APPLICATION in my settings.

**Comment by ingenieroariel** [comment] 2016-08-03 20:45
@capooti the correct location is within the hypermap folder, so that it can be accessed as hypermap.wsgi. It did not work in your case because within that wsgi file, hypermap was trying to be loaded but you had not installed it in your local python. (pip install -e)

When we set up hypermap for development or production, we should make sure we can do 'import hypermap' from anything in the filesystem instead of just when we are in the project root. That will avoid any relative imports that make the app less portable.

**Comment by capooti** [comment] 2016-08-03 21:26
thanks @ingenieroariel
